[package]
name = "brz-mysql-derive"
version = "0.0.6"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/we-breeze/mysql"
description = "Derive macros for brz-mysql row and column conversion"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
